name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macOS-10.15, windows-2019]
        python-version: [3.6, 3.9]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: pip install -e .
      - name: Try pretrain avg
        run:  python -m varclr.pretrain --model avg --name varclr-avg --epochs 1 --gpu 0
      - name: Try pretrain lstm
        run:  python -m varclr.pretrain --model lstm --name varclr-lstm --epochs 1 --gpu 0
      - name: Try pretrain bert
        run: python -m varclr.pretrain --model bert --name varclr-codebert --epochs 1 --sp-model split  --last-n-layer-output 4 --batch-size 64 --lr 1e-5 --gpu 0
